// Glass Canyon: winding valleys between six mesas, between Dunmere and the Hollow.
// 56×36 tiles. The Hollow's golden door sits in the north-east cliff face and needs
// three Sun Shards. The old mining yard is fenced and its gate needs the Chain Key.
export default {
  id: 'canyon',
  name: 'Glass Canyon',
  subtitle: 'The road east',
  music: 'canyon',
  ambient: 'canyon',
  faceRows: 2,
  ground: [
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
    'PPPP..................TTTTTTTTTTT.....................TT',
    'PPPP..................TTTTTTTTTTT.....................TT',
    'PPPP..PPPPPPPPPPP.....TTTTTTTTTTT.....GGGGGGGGGGGGG...TT',
    'PPPP..PPPPPPPPPPP.....TTTTTTTTTTT.....GGGGGGGGGGGGG...TT',
    'PPPP..PPPPPPPPPPP.....TTTTTTTTTTT.....GGGGGGGGGGGGG...TT',
    'PPPP..PPPPPPPPPPP.....TTTTTTTTTTT.....GGGGGGGGGGGGG...TT',
    'PPPP..PPPPPPPPPPP.....................GGGGGGGGGGGGG...TT',
    'PPPP..PPPPPPPPPPP.....................GGGGGGGGGGGGG...TT',
    'PPPP..PPPPPPPPPPP.....................GGGGGGGGGGGGG...TT',
    'PPPP..................................GGGGGGGGGGGGG...TT',
    '....,,,,,,,,,,,,,,,,,.................,,,,,,,,........TT',
    '....,,,,,,,,,,,,,,,,,.................,,,,,,,,........TT',
    '............................................TTTTTTTTT.TT',
    'PPPP........................................TTTTTTTTT.TT',
    'PPPP........................................TTTTTTTTT.TT',
    'PPPP..........PPPPPPPPPPP...................TTTTTTTTT.TT',
    'PPPP..........PPPPPPPPPPP...................TTTTTTTTT.TT',
    'PPPP..........PPPPPPPPPPP.....GGGGGGGGGGG.............TT',
    'PPPP..........PPPPPPPPPPP.....GGGGGGGGGGG.............TT',
    'PPPP..........PPPPPPPPPPP.....GGGGGGGGGGG.............TT',
    'PPPP..........PPPPPPPPPPP.....GGGGGGGGGGG.............TT',
    'PPPP..........................GGGGGGGGGGG.............TT',
    'PPPP..........................GGGGGGGGGGG.............TT',
    'PPPP........................................,,,,,.....TT',
    'PPPP........................................,,,,,.....TT',
    'PPPP..................................................TT',
    'PPPP..................................................TT',
    'PPPP..................................................TT',
    'PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP',
    'PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP',
    'PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP',
    'PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP',
  ],
  props: [
    '                                                        ',
    '                                                        ',
    '                                                        ',
    '                                                        ',
    '                                                        ',
    '                                 R  C                   ',
    '                                                        ',
    '                        T          o                    ',
    '                                                        ',
    '                                                        ',
    '          Y                                             ',
    '                                            T           ',
    '                                                        ',
    '                    A         C                         ',
    '                                                        ',
    '                        o     o                         ',
    '    CCCC  C       ^                 C                   ',
    '     c   c                                              ',
    '            R              A            o       T       ',
    '                                                        ',
    '                           C              ^             ',
    '                                                        ',
    '        C        Y       o                 R            ',
    '                                                        ',
    '           ^                      T          c          ',
    '                                                        ',
    '                            C                     o     ',
    '      K                                   ____  _____   ',
    '                                          : X     b ;   ',
    '                                          :         ;   ',
    '                            R             :  x      ;   ',
    '                                          ___________   ',
    '                                                        ',
    '                                                        ',
    '                                                        ',
    '                                                        ',
  ],
  objects: [
    // The Hollow's sealed door, set into the cliff face of the north-east mesa.
    { type: 'tiles', x: 42, y: 12, tiles: [[188, 189], [206, 207]], solid: true },
    { type: 'action', id: 'hollow_door', x: 42, y: 13, w: 2, h: 1 },
    // The mining yard gate, locked until the Chain Key turns up.
    { type: 'blocker', id: 'yard_gate', x: 46, y: 27, w: 2, h: 1, tile: 214, art: 'padlock' },
    { type: 'chest', id: 'canyon_secret', x: 6, y: 15, color: 'gold', secret: true, contents: { items: { prickly_pie: 1 }, dollars: 30 } },
    { type: 'chest', id: 'canyon_dew', x: 35, y: 5, color: 'orange', contents: { items: { fizzy_dew: 2 } } },
    { type: 'chest', id: 'canyon_key', x: 52, y: 9, color: 'orange', contents: { keys: ['chain_key'] } },
    { type: 'chest', id: 'canyon_shard1', x: 9, y: 27, color: 'gold', contents: { keys: ['sun_shard'] } },
    { type: 'chest', id: 'canyon_shard2', x: 48, y: 29, color: 'gold', contents: { keys: ['sun_shard'] } },
    { type: 'terminal', x: 44, y: 29 },
    { type: 'sign', x: 22, y: 14, style: 'green', text: 'sign_canyon_east' },
    { type: 'sign', x: 40, y: 15, style: 'red', text: 'sign_hollow' },
    { type: 'exit', x: 0, y: 14, w: 1, h: 3, to: 'dunmere', spawn: 'east' },
  ],
  spawns: {
    west: { x: 2, y: 15, facing: 'right' },
    hollow: { x: 42.5, y: 14, facing: 'down' },
  },
};
