// Dunmere, the oasis town: a valley ringed by mesas, the Gate plaza in the middle.
// 44×30 tiles. Legend: see src/world/map.js and src/data/tiles.js.
export default {
  id: 'dunmere',
  name: 'Dunmere',
  subtitle: 'Oasis Town',
  music: 'town',
  ambient: 'town',
  faceRows: 2,
  ground: [
    'TTTTPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPGGGG',
    'TTTTPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPGGGG',
    'TTTTPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPGGGG',
    'TTTTPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPGGGG',
    'TTTT...............PPPPPPP..............GGGG',
    'TTTT...............PPPPPPP..............GGGG',
    'TTTT....................................GGGG',
    'TTTT....................................GGGG',
    'TTTT.............===========............GGGG',
    'TTTT.............===========.....,,.ppppGGGG',
    'TTTT...,,........===========,,,,,,,.ppppGGGG',
    'TTTT...,,,,,,,,,,===========,,,,,,,.ppppGGGG',
    'TTTT...,,,,,,,,,,===========.....,,.....GGGG',
    'TTTT.ttttttt.....===========,,,,,,,,,,,,,,,,',
    'TTTT.ttttttt.....===========,,,,,,,,,,,,,,,,',
    'TTTT.ttttttt................................',
    'TTTT.ttttttt................................',
    'TTTT.ttttttt......pppppppp..............GGGG',
    'TTTT..............pppppppp..............GGGG',
    'TTTT..............pppppppp..............GGGG',
    'TTTT..............pppppppp..............GGGG',
    'TTTT....................................GGGG',
    'TTTT....................................GGGG',
    'TTTT....................................GGGG',
    'TTTT....................................GGGG',
    'TTTT....................................GGGG',
    'TTTTPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPGGGG',
    'TTTTPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPGGGG',
    'TTTTPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPGGGG',
    'TTTTPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPGGGG',
  ],
  props: [
    '                                            ',
    '                                            ',
    '                                            ',
    '                                            ',
    '    C   R                                   ',
    '          T     B R        T          T     ',
    '    T                     R B       x       ',
    '                                    x  C    ',
    '                                            ',
    '          b     L h       h L       g       ',
    '                                      Y     ',
    '                                     g      ',
    '                                     L      ',
    '              o   H       H                 ',
    '    T   v                          o        ',
    '     v     v    L           L o             ',
    '       v    T                         c     ',
    '      T   T                                 ',
    '                   g    Y             x     ',
    '      ---  ---  c        gC     b      R    ',
    '     c|      !     Y   g              ^     ',
    '      |C c C ! C          T  ___  _____     ',
    '    C |      !      o        :Xx    Xx;     ',
    '      | c C c!   C    R    c :        ;     ',
    '      --------          A    :bB     b;C    ',
    '     ^         T             __________     ',
    '                                            ',
    '                                            ',
    '                                            ',
    '                                            ',
  ],
  objects: [
    { type: 'building', id: 'nana_house', x: 5, y: 6, w: 5, roof: 2, wall: 2, door: { dx: 2, kind: 'red', to: 'house', spawn: 'door' } },
    { type: 'building', id: 'mayor_house', x: 11, y: 5, w: 5, roof: 2, wall: 2, door: { dx: 2, kind: 'red', text: 'mayor_door' } },
    {
      type: 'building', id: 'post_office', x: 29, y: 4, w: 7, roof: 2, wall: 3,
      door: { dx: 5, kind: 'red', to: 'post', spawn: 'door' },
      decor: [{ dx: 1, kind: 'shutter' }],
    },
    { type: 'building', id: 'workshop', x: 33, y: 17, w: 5, roof: 1, wall: 3, door: { dx: 2, kind: 'doorway', text: 'workshop_door' } },
    { type: 'gate', id: 'dunmere_gate', x: 21, y: 9 },
    { type: 'sign', x: 20, y: 13, style: 'red', text: 'sign_gate' },
    { type: 'sign', x: 28, y: 8, style: 'green', text: 'sign_post' },
    { type: 'sign', x: 12, y: 13, style: 'green', text: 'sign_town' },
    { type: 'sign', x: 38, y: 15, style: 'green', text: 'sign_canyon' },
    { type: 'chest', id: 'town_a', x: 37, y: 4, color: 'orange', contents: { items: { cactus_candy: 2 } } },
    { type: 'exit', x: 43, y: 13, w: 1, h: 4, to: 'canyon', spawn: 'west' },
  ],
  spawns: {
    door: { x: 7, y: 10, facing: 'down' },
    post: { x: 34, y: 9, facing: 'down' },
    east: { x: 41, y: 14, facing: 'left' },
    gate: { x: 22, y: 13, facing: 'up' },
  },
};
