// The Hollow: a rock labyrinth under Glass Canyon. Entry hall with a Post Terminal,
// a west room, the rune pad chamber, and Grumblejaw's chamber around the dark Gate.
// 36×30 tiles. Walls are two rows thick so the rock gets a proper edge; faceRows 1
// keeps those edges tight.
export default {
  id: 'hollow',
  name: 'The Hollow',
  subtitle: 'Under the canyon',
  music: 'hollow',
  ambient: 'cave',
  indoors: true,
  light: 'cave',
  faceRows: 1,
  ground: [
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
    'GGGGGGGGGGGG.................GGGGGGG',
    'GGGGGGGGGGGG.................GGGGGGG',
    'GGGGGGGGGGGG.................GGGGGGG',
    'GGGGGGGGGGGG.................GGGGGGG',
    'GGGGGGGGGGGG.................GGGGGGG',
    'GGGGGGGGGGGG.................GGGGGGG',
    'GGGGGGGGGGGGGGGGGGGGG..GGGGGGGGGGGGG',
    'GGGGGGGGGGGGGGGGGGGGG..GGGGGGGGGGGGG',
    'GGGGGGGGGGGGGGGG...............GGGGG',
    'GGGGGGGGGGGGGGGG...............GGGGG',
    'GGGG..........GG...............GGGGG',
    'GGGG..........GG...............GGGGG',
    'GGGG..........GG...............GGGGG',
    'GGGG..........GG...............GGGGG',
    'GGGG...........................GGGGG',
    'GGGG...........................GGGGG',
    'GGGG..........GG...............GGGGG',
    'GGGG..........GG...............GGGGG',
    'GGGGGGGGGGGGGGGGG..GGGGGGGGGGGGGGGGG',
    'GGGGGGGGGGGGGGGGG..GGGGGGGGGGGGGGGGG',
    'GGGGGGGGGGGG............GGGGGGGGGGGG',
    'GGGGGGGGGGGG............GGGGGGGGGGGG',
    'GGGGGGGGGGGG............GGGGGGGGGGGG',
    'GGGGGGGGGGGG............GGGGGGGGGGGG',
    'GGGGGGGGGGGG............GGGGGGGGGGGG',
    'GGGGGGGGGGGG............GGGGGGGGGGGG',
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
  ],
  props: [
    '                                    ',
    '                                    ',
    '                                    ',
    '                                    ',
    '                          v         ',
    '              v                     ',
    '               R         R          ',
    '                                    ',
    '                                    ',
    '                                    ',
    '                                    ',
    '                  ^         v       ',
    '                                    ',
    '     bv     b                       ',
    '                                    ',
    '                                    ',
    '                                    ',
    '                                    ',
    '        R                           ',
    '         K v                 R      ',
    '                                    ',
    '                                    ',
    '                                    ',
    '                   v                ',
    '                                    ',
    '             R                      ',
    '                      v             ',
    '                                    ',
    '                                    ',
    '                                    ',
  ],
  objects: [
    // The pad chamber's door: a golden arch, opened by stepping the pads in order.
    { type: 'blocker', id: 'pad_door', x: 21, y: 8, w: 2, h: 2, tiles: [[188, 189], [206, 207]] },
    { type: 'pad', id: 'pad_rise', glyph: 'glyphRise', x: 18, y: 13 },
    { type: 'pad', id: 'pad_sun', glyph: 'glyphSun', x: 22, y: 13 },
    { type: 'pad', id: 'pad_moon', glyph: 'glyphMoon', x: 26, y: 13 },
    { type: 'sign', x: 22, y: 17, style: 'green', text: 'sign_pads' },
    { type: 'gate', id: 'hollow_gate', x: 19, y: 3 },
    { type: 'chest', id: 'hollow_tea', x: 6, y: 14, color: 'orange', contents: { items: { sun_tea: 1 } } },
    { type: 'chest', id: 'hollow_bombs', x: 28, y: 11, color: 'orange', contents: { items: { dust_bomb: 2 } } },
    { type: 'terminal', x: 14, y: 24 },
    { type: 'trigger', x: 21, y: 7, w: 2, h: 1, script: 'boss_room' },
    { type: 'exit', x: 17, y: 27, w: 2, h: 1, to: 'canyon', spawn: 'hollow' },
  ],
  spawns: {
    entry: { x: 17.5, y: 26, facing: 'up' },
    boss: { x: 21.5, y: 7, facing: 'up' },
  },
};
